spring:
  profiles:
    active: local

server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types:
      text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, application/xml


